# Generated by Django 2.2.3 on 2019-07-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_model_no', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=600)),
                ('color_combination', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('url_image', models.CharField(max_length=2083)),
            ],
        ),
    ]
