# Generated by Django 2.2.3 on 2019-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image_url',
            field=models.CharField(default=True, max_length=2083),
            preserve_default=False,
        ),
    ]
